---
- name: "Infrastructure système"
  hosts: k8s_cluster
  become: true
  handlers:
    - name: Restart Rsyslog
      service: name=rsyslog state=restarted

    - name: Reload NFTables
      service: name=nftables state=reloaded

    - name: Restart SSH
      service: name=ssh state=restarted

  roles:
    - role: clean
      tags: ["never", "clean"]
    - role: common
      tags: ["common", "system"]

- name: "Cluster Kubernetes"
  hosts: k8s_cluster
  become: true
  tags: ["k8s", "kubernetes"]
  handlers:
    - name: Reload NFTables
      service: name=nftables state=reloaded

  roles:
    - k8s

- name: "Applications Kubernetes"
  hosts: server
  become: true
  tags: ["app_k8s"]
  
  roles:
    - app_k8s

- name: "Runners Kubernetes"
  hosts: server
  become: true
  tags: ["k8s_runner"]
  
  roles:
    - runner

- name: "Audit de securite"
  hosts: k8s_cluster
  become: true
  gather_facts: yes
  tags: ["never", "audit"]
  roles:
    - audit_security
