---
- name: Sécurisation des serveurs OVH Debian 12 (Mode Paranoïaque)
  hosts: swarm_nodes
  become: yes
  vars:
    sysadmin_user: "supadmin"
    sysadmin_password: "!" 
    new_ssh_port: 49281
    local_public_key: "~/.ssh/id_rsa.pub"
    
  tasks:
    # --- 1. CONFIGURATION SYSTEME & UTILISATEUR ---
    
    - name: Mise à jour du cache APT et upgrade
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Création de l'utilisateur {{ sysadmin_user }}
      user:
        name: "{{ sysadmin_user }}"
        password: "{{ sysadmin_password }}"
        groups: sudo
        shell: /bin/bash
        append: yes
        state: present

    - name: Copie de la clé SSH pour {{ sysadmin_user }}
      authorized_key:
        user: "{{ sysadmin_user }}"
        state: present
        key: "{{ lookup('file', local_public_key) }}"

    - name: Sudo sans mot de passe pour {{ sysadmin_user }}
      copy:
        dest: "/etc/sudoers.d/{{ sysadmin_user }}"
        content: "{{ sysadmin_user }} ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Création user dockremap (anticipation Docker)
      user:
        name: dockremap
        system: yes
        shell: /usr/sbin/nologin
        create_home: no
        state: present

    - name: Installation des paquets de sécurité
      apt:
        pkg:
          - nftables
          - fail2ban
          - sudo
          - curl
        state: present

    # --- 2. PARE-FEU (CRITIQUE) ---
    
    - name: Configuration NFTables (Double Porte)
      copy:
        dest: /etc/nftables.conf
        content: |
          #!/usr/sbin/nft -f
          flush ruleset

          table inet filter {
            chain input {
              type filter hook input priority 0; policy drop;
              iifname "lo" accept
              ct state established,related accept
              ip protocol icmp accept
              ip6 nexthdr icmpv6 accept

              # 1. On ouvre le NOUVEAU port
              tcp dport {{ new_ssh_port }} accept
              
              # 2. On garde l'ANCIEN port ouvert (Sécurité anti-coupure)
              tcp dport 22 accept
            }
            chain forward {
              type filter hook forward priority 0; policy drop;
            }
            chain output {
              type filter hook output priority 0; policy accept;
            }
          }
        mode: '0755'

    # SECURITE : On force le reload MAINTENANT, pas à la fin du playbook
    - name: Rechargement immédiat de NFTables
      service:
        name: nftables
        state: reloaded
        enabled: yes

    # --- 3. CONFIGURATION SSH (CRITIQUE) ---

    - name: Durcissement SSHD (Changement de port)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?Port', line: "Port {{ new_ssh_port }}" }
        - { regexp: '^#?PermitRootLogin', line: "PermitRootLogin no" }
        - { regexp: '^#?PasswordAuthentication', line: "PasswordAuthentication no" }
        - { regexp: '^#?PubkeyAuthentication', line: "PubkeyAuthentication yes" }
        - { regexp: '^#?X11Forwarding', line: "X11Forwarding no" }
        # On s'assure que SSH n'inclut pas d'autres fichiers qui écraseraient nos configs
        - { regexp: '^#?Include', line: "#Include /etc/ssh/sshd_config.d/*.conf" }

    # SECURITE : On vérifie la syntaxe avant de redémarrer
    - name: Vérification de la configuration SSHD
      command: sshd -t
      changed_when: false

    # On redémarre SSH. La session Ansible actuelle ne devrait pas couper,
    # car elle est "established" dans le pare-feu et SSH ne tue pas les processus fils actifs.
    - name: Redémarrage immédiat de SSH
      service:
        name: ssh
        state: restarted

    # --- 4. FAIL2BAN ---

    - name: Protection SSH avec Fail2Ban
      copy:
        dest: /etc/fail2ban/jail.d/ssh_custom.conf
        content: |
          [sshd]
          enabled = true
          port = {{ new_ssh_port }}
          bantime = 1h
          findtime = 10m
          maxretry = 5
      notify: Restart Fail2Ban

  handlers:
    - name: Restart Fail2Ban
      service: name=fail2ban state=restarted